### ISSUE TITLE
Error line 172 $less->ImportDir[] 

### ISSUE THREAD

**Issue by AndyBaumann** [lupo49/dokuwiki-plugin-fontcolor#14]
Same problem as described here:
https://github.com/splitbrain/dokuwiki/issues/1777

PHP Fatal error:  Uncaught Error: [] operator not supported for strings in C:\xxxxxxx\lib\plugins\fontcolor\syntax.php:172

Changing line 172 from
$less->importDir[] = DOKU_INC;
to
$less->importDir = array(DOKU_INC);

worked for me on PHP 7.1.17.0

**Comment by Klap-in** [comment]
Solved by #20
