### ISSUE TITLE
Error: Class 'lessc' not found after upgrade to Dokuwiki version 2024-02-06 "Kaos"

### ISSUE THREAD

**Issue by dipohl** [lupo49/dokuwiki-plugin-fontcolor#18]
On every page using the fontcolor plugin I get this error message:
> Error: Class 'lessc' not found
> 
> An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the fontcolor plugin.
> 
> More info has been written to the DokuWiki error log.

2024-02-11 12:56:04Error: Class 'lessc' not found/usr/share/nginx/html/dokuwiki/lib/plugins/fontcolor/syntax.php(171)
    #0 /usr/share/nginx/html/dokuwiki/lib/plugins/fontcolor/syntax.php(97): syntax_plugin_fontcolor->_color2hexdec()
    #1 /usr/share/nginx/html/dokuwiki/inc/parser/handler.php(298): syntax_plugin_fontcolor->handle()
    #2 /usr/share/nginx/html/dokuwiki/inc/Parsing/Lexer/Lexer.php(269): Doku_Handler->plugin()
    #3 /usr/share/nginx/html/dokuwiki/inc/Parsing/Lexer/Lexer.php(203): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
    #4 /usr/share/nginx/html/dokuwiki/inc/Parsing/Lexer/Lexer.php(146): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
    #5 /usr/share/nginx/html/dokuwiki/inc/Parsing/Parser.php(113): dokuwiki\Parsing\Lexer\Lexer->parse()
    #6 /usr/share/nginx/html/dokuwiki/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #7 /usr/share/nginx/html/dokuwiki/inc/parserutils.php(198): p_get_instructions()
    #8 /usr/share/nginx/html/dokuwiki/inc/parserutils.php(520): p_cached_instructions()
    #9 /usr/share/nginx/html/dokuwiki/inc/parserutils.php(299): p_render_metadata()
    #10 /usr/share/nginx/html/dokuwiki/inc/common.php(262): p_get_metadata()
    #11 /usr/share/nginx/html/dokuwiki/doku.php(101): pageinfo()
    #12 {main}

**Comment by waltkind** [comment]
I have the same problem. 
Will this issue be solved or is this plugin orphaned?

**Comment by Klap-in** [comment]
Since Kaos an updated class of lessc with different naming scheme is used. A if else must be added that checks of the new class exits, and use that or the old one.

A pull request is welcome :-)
Otherwise I will do it at some point.

**Comment by michitux** [comment]
> Ah, wait a moment, I have no commit rights here. 

I have commit rights, but no admin right. I can merge PRs.

**Comment by dipohl** [comment]
I moved to plugin 'color' https://www.dokuwiki.org/plugin:color which supports same and enhanced functions and has more recent version from 2022-10-19

**Comment by virk** [comment]
@dipohl: I also switched over to color plugin. I applied the following changes:
    * In Datei script.js
      * </color durch </fc und
      * <color durch <fc ersetzen
    * In syntax.php Zeile 21 </color durch </fc und <color durch <fc ersetzen
    * In syntax.php Zeile 22 </color> durch </fc> ersetzen 
    * In syntax.php Zeile 31 die 6" durch eine "3" ersetzen.
and now color plugin "completely" replaces the font color-plugin and I did not need to change the syntax of old pages.

**Comment by waltkind** [comment]
Thanks to your hints, I also moved to the color plugin  that solved my problems.

**Comment by dipohl** [comment]
@virk : Thanks that you wanted to help :-)

Instead of your recipe to make changes in the Color plugin
>     * In Datei script.js
>     * In syntax.php 
> and now color plugin "completely" replaces the font color-plugin and I did not need to change the syntax of old pages.

I used plugin 'BatchEdit' https://www.dokuwiki.org/plugin:batchedit
to change all Syntax in the wiki pages:
<fc -> <color
</fc -> </color

This way I can update the 'color' plugin without need to patch it again and again and again ;-)

HTH and kind regards

**Comment by virk** [comment]
@dipohl Yes, I was also thinking about that possibility. Here we have 8000 pages organized in 100s of namespaces; I was a little bit afraid, that batch edit perhaps does not do the job correctly. Currently I am thinking about the possibility to double the color plugin so that old pages will be rendered with adjusted to <fc- plugin and new pages handled normally.
But currently I documented the applied changes well and can reapply them in case an update of color plugin will show up.
Are you German? I am from Aachen. Greetings Heiner
